/* SPLPrime.java */
/* Generated By:JavaCC: Do not edit this line. SPLPrime.java */
package splprime.generated_scan;
import splprime.ast_generated.*;
import java.util.List;
import java.util.ArrayList;

public class SPLPrime implements SPLPrimeConstants {
      /** Main entry point. */
      public static void main(String args[]) throws ParseException {
        SPLPrime parser = new SPLPrime(System.in);
        parser.program();
      }

/** Top level production. */
  static final public List<Stmt> program() throws ParseException {List<Stmt> stmts = new ArrayList<Stmt>(); Stmt s;
    label_1:
    while (true) {
      if (jj_2_1(2)) {
        ;
      } else {
        break label_1;
      }
      s = declaration();
stmts.add(s);
    }
    jj_consume_token(0);
{if ("" != null) return stmts;}
    throw new Error("Missing return statement in function");
}

  static final public Stmt declaration() throws ParseException {Stmt s;
    if (jj_2_2(2)) {
      s = varDecl();
{if ("" != null) return s;}
    } else if (jj_2_3(2)) {
      s = statement();
{if ("" != null) return s;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public Var varDecl() throws ParseException {Expr e = null; splprime.generated_scan.Token name;
    jj_consume_token(VAR);
    name = jj_consume_token(IDENTIFIER);
    if (jj_2_4(2)) {
      jj_consume_token(EQUAL);
      e = expression();
    } else {
      ;
    }
    jj_consume_token(SEMICOLON);
{if ("" != null) return new Var(name, e);}
    throw new Error("Missing return statement in function");
}

  static final public Stmt statement() throws ParseException {Stmt s;
    if (jj_2_5(2)) {
      s = exprStmt();
{if ("" != null) return s;}
    } else if (jj_2_6(2)) {
      s = ifStmt();
{if ("" != null) return s;}
    } else if (jj_2_7(2)) {
      s = printStmt();
{if ("" != null) return s;}
    } else if (jj_2_8(2)) {
      s = whileStmt();
{if ("" != null) return s;}
    } else if (jj_2_9(2)) {
      s = block();
{if ("" != null) return s;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public ExprStmt exprStmt() throws ParseException {Expr e;
    e = expression();
    jj_consume_token(SEMICOLON);
{if ("" != null) return new ExprStmt(e);}
    throw new Error("Missing return statement in function");
}

  static final public IfStmt ifStmt() throws ParseException {Expr e; Stmt then_stmt; Stmt else_stmt = null;
    jj_consume_token(IF);
    jj_consume_token(LEFT_PAREN);
    e = expression();
    jj_consume_token(RIGHT_PAREN);
    then_stmt = statement();
    if (jj_2_10(2)) {
      jj_consume_token(ELSE);
      else_stmt = statement();
    } else {
      ;
    }
{if ("" != null) return new IfStmt(e, then_stmt, else_stmt);}
    throw new Error("Missing return statement in function");
}

  static final public PrintStmt printStmt() throws ParseException {Expr e;
    jj_consume_token(PRINT);
    e = expression();
    jj_consume_token(SEMICOLON);
{if ("" != null) return new PrintStmt(e);}
    throw new Error("Missing return statement in function");
}

  static final public WhileStmt whileStmt() throws ParseException {Expr e; Stmt s;
    jj_consume_token(WHILE);
    jj_consume_token(LEFT_PAREN);
    e = expression();
    jj_consume_token(RIGHT_PAREN);
    s = statement();
{if ("" != null) return new WhileStmt(e, s);}
    throw new Error("Missing return statement in function");
}

  static final public Block block() throws ParseException {List<Stmt> stmts = new ArrayList<Stmt>(); Stmt s;
    jj_consume_token(LEFT_BRACE);
    label_2:
    while (true) {
      if (jj_2_11(2)) {
        ;
      } else {
        break label_2;
      }
      s = declaration();
stmts.add(s);
    }
    jj_consume_token(RIGHT_BRACE);
{if ("" != null) return new Block(stmts);}
    throw new Error("Missing return statement in function");
}

  static final public Expr expression() throws ParseException {Expr e;
    e = assignment();
{if ("" != null) return e;}
    throw new Error("Missing return statement in function");
}

  static final public Expr assignment() throws ParseException {Expr e; splprime.generated_scan.Token name;
    if (jj_2_12(2)) {
      // Check if it's "ID ="
          name = jj_consume_token(IDENTIFIER);
      jj_consume_token(EQUAL);
      e = assignment();
{if ("" != null) return new Assign(name, e);}
    } else if (jj_2_13(2)) {
      e = logic_or();
{if ("" != null) return e;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public Expr logic_or() throws ParseException {Expr left; Expr right; splprime.generated_scan.Token op;
    left = logic_and();
    label_3:
    while (true) {
      if (jj_2_14(2)) {
        ;
      } else {
        break label_3;
      }
      op = jj_consume_token(OR);
      right = logic_and();
left = new BinaryExpr(left, op, right);
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  static final public Expr logic_and() throws ParseException {Expr left; Expr right; splprime.generated_scan.Token op;
    left = equality();
    label_4:
    while (true) {
      if (jj_2_15(2)) {
        ;
      } else {
        break label_4;
      }
      op = jj_consume_token(AND);
      right = equality();
left = new BinaryExpr(left, op, right);
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  static final public Expr equality() throws ParseException {Expr left; Expr right; splprime.generated_scan.Token op;
    left = comparison();
    label_5:
    while (true) {
      if (jj_2_16(2)) {
        ;
      } else {
        break label_5;
      }
      if (jj_2_17(2)) {
        op = jj_consume_token(NOT_EQUAL);
      } else if (jj_2_18(2)) {
        op = jj_consume_token(EQUAL_EQUAL);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
      right = comparison();
left = new BinaryExpr(left, op, right);
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  static final public Expr comparison() throws ParseException {Expr left; Expr right; splprime.generated_scan.Token op;
    left = term();
    label_6:
    while (true) {
      if (jj_2_19(2)) {
        ;
      } else {
        break label_6;
      }
      if (jj_2_20(2)) {
        op = jj_consume_token(GREATER);
      } else if (jj_2_21(2)) {
        op = jj_consume_token(GREATER_EQUAL);
      } else if (jj_2_22(2)) {
        op = jj_consume_token(LESS);
      } else if (jj_2_23(2)) {
        op = jj_consume_token(LESS_EQUAL);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
      right = term();
left = new BinaryExpr(left, op, right);
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  static final public Expr term() throws ParseException {Expr left; Expr right; splprime.generated_scan.Token op;
    left = factor();
    label_7:
    while (true) {
      if (jj_2_24(2)) {
        ;
      } else {
        break label_7;
      }
      if (jj_2_25(2)) {
        op = jj_consume_token(PLUS);
      } else if (jj_2_26(2)) {
        op = jj_consume_token(MINUS);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
      right = factor();
left = new BinaryExpr(left, op, right);
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  static final public Expr factor() throws ParseException {Expr left; Expr right; splprime.generated_scan.Token op;
    left = unary();
    label_8:
    while (true) {
      if (jj_2_27(2)) {
        ;
      } else {
        break label_8;
      }
      if (jj_2_28(2)) {
        op = jj_consume_token(DIVIDE);
      } else if (jj_2_29(2)) {
        op = jj_consume_token(STAR);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
      right = unary();
left = new BinaryExpr(left, op, right);
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  static final public Expr unary() throws ParseException {splprime.generated_scan.Token t; Expr e;
    if (jj_2_32(2)) {
      if (jj_2_30(2)) {
        t = jj_consume_token(NOT);
      } else if (jj_2_31(2)) {
        t = jj_consume_token(MINUS);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
      e = unary();
{if ("" != null) return new UnaryExpr(t, e);}
    } else if (jj_2_33(2)) {
      e = primary();
{if ("" != null) return e;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public Expr primary() throws ParseException {splprime.generated_scan.Token t; Expr e;
    if (jj_2_34(2)) {
      // Pass the actual boolean value
          t = jj_consume_token(TRUE);
{if ("" != null) return new Literal(true);}
    } else if (jj_2_35(2)) {
      t = jj_consume_token(FALSE);
{if ("" != null) return new Literal(false);}
    } else if (jj_2_36(2)) {
      t = jj_consume_token(NUMBER);
Object val;
                       if (t.image.contains(".")) {
                           val = Double.parseDouble(t.image);
                       } else {
                           val = Integer.parseInt(t.image);
                       }
                       {if ("" != null) return new Literal(val);}
    } else if (jj_2_37(2)) {
      t = jj_consume_token(STRING);
String s = t.image.substring(1, t.image.length() - 1);
                       {if ("" != null) return new Literal(s);}
    } else if (jj_2_38(2)) {
      jj_consume_token(LEFT_PAREN);
      e = expression();
      jj_consume_token(RIGHT_PAREN);
{if ("" != null) return new Grouping(e);}
    } else if (jj_2_39(2)) {
      t = jj_consume_token(IDENTIFIER);
{if ("" != null) return new Variable(t);}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_3()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_4()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_2_5(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_5()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  static private boolean jj_2_6(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_6()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  static private boolean jj_2_7(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_7()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  static private boolean jj_2_8(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_8()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  static private boolean jj_2_9(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_9()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  static private boolean jj_2_10(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_10()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  static private boolean jj_2_11(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_11()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  static private boolean jj_2_12(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_12()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  static private boolean jj_2_13(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_13()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  static private boolean jj_2_14(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_14()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  static private boolean jj_2_15(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_15()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(14, xla); }
  }

  static private boolean jj_2_16(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_16()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(15, xla); }
  }

  static private boolean jj_2_17(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_17()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(16, xla); }
  }

  static private boolean jj_2_18(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_18()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(17, xla); }
  }

  static private boolean jj_2_19(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_19()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(18, xla); }
  }

  static private boolean jj_2_20(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_20()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(19, xla); }
  }

  static private boolean jj_2_21(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_21()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(20, xla); }
  }

  static private boolean jj_2_22(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_22()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(21, xla); }
  }

  static private boolean jj_2_23(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_23()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(22, xla); }
  }

  static private boolean jj_2_24(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_24()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(23, xla); }
  }

  static private boolean jj_2_25(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_25()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(24, xla); }
  }

  static private boolean jj_2_26(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_26()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(25, xla); }
  }

  static private boolean jj_2_27(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_27()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(26, xla); }
  }

  static private boolean jj_2_28(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_28()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(27, xla); }
  }

  static private boolean jj_2_29(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_29()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(28, xla); }
  }

  static private boolean jj_2_30(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_30()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(29, xla); }
  }

  static private boolean jj_2_31(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_31()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(30, xla); }
  }

  static private boolean jj_2_32(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_32()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(31, xla); }
  }

  static private boolean jj_2_33(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_33()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(32, xla); }
  }

  static private boolean jj_2_34(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_34()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(33, xla); }
  }

  static private boolean jj_2_35(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_35()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(34, xla); }
  }

  static private boolean jj_2_36(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_36()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(35, xla); }
  }

  static private boolean jj_2_37(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_37()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(36, xla); }
  }

  static private boolean jj_2_38(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_38()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(37, xla); }
  }

  static private boolean jj_2_39(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_39()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(38, xla); }
  }

  static private boolean jj_3R_varDecl_88_5_10()
 {
    if (jj_scan_token(VAR)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  static private boolean jj_3_17()
 {
    if (jj_scan_token(NOT_EQUAL)) return true;
    return false;
  }

  static private boolean jj_3_3()
 {
    if (jj_3R_statement_94_5_11()) return true;
    return false;
  }

  static private boolean jj_3_16()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_17()) {
    jj_scanpos = xsp;
    if (jj_3_18()) return true;
    }
    if (jj_3R_comparison_185_5_21()) return true;
    return false;
  }

  static private boolean jj_3R_declaration_82_5_9()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_2()) {
    jj_scanpos = xsp;
    if (jj_3_3()) return true;
    }
    return false;
  }

  static private boolean jj_3_2()
 {
    if (jj_3R_varDecl_88_5_10()) return true;
    return false;
  }

  static private boolean jj_3R_equality_174_5_20()
 {
    if (jj_3R_comparison_185_5_21()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_16()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3_1()
 {
    if (jj_3R_declaration_82_5_9()) return true;
    return false;
  }

  static private boolean jj_3_15()
 {
    if (jj_scan_token(AND)) return true;
    if (jj_3R_equality_174_5_20()) return true;
    return false;
  }

  static private boolean jj_3R_logic_and_163_5_19()
 {
    if (jj_3R_equality_174_5_20()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_15()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3_14()
 {
    if (jj_scan_token(OR)) return true;
    if (jj_3R_logic_and_163_5_19()) return true;
    return false;
  }

  static private boolean jj_3_39()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  static private boolean jj_3R_logic_or_152_5_18()
 {
    if (jj_3R_logic_and_163_5_19()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_14()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3_23()
 {
    if (jj_scan_token(LESS_EQUAL)) return true;
    return false;
  }

  static private boolean jj_3_38()
 {
    if (jj_scan_token(LEFT_PAREN)) return true;
    if (jj_3R_expression_139_5_12()) return true;
    return false;
  }

  static private boolean jj_3_13()
 {
    if (jj_3R_logic_or_152_5_18()) return true;
    return false;
  }

  static private boolean jj_3R_assignment_145_5_26()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_12()) {
    jj_scanpos = xsp;
    if (jj_3_13()) return true;
    }
    return false;
  }

  static private boolean jj_3_37()
 {
    if (jj_scan_token(STRING)) return true;
    return false;
  }

  static private boolean jj_3_12()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(EQUAL)) return true;
    return false;
  }

  static private boolean jj_3R_expression_139_5_12()
 {
    if (jj_3R_assignment_145_5_26()) return true;
    return false;
  }

  static private boolean jj_3_22()
 {
    if (jj_scan_token(LESS)) return true;
    return false;
  }

  static private boolean jj_3_31()
 {
    if (jj_scan_token(MINUS)) return true;
    return false;
  }

  static private boolean jj_3_29()
 {
    if (jj_scan_token(STAR)) return true;
    return false;
  }

  static private boolean jj_3_11()
 {
    if (jj_3R_declaration_82_5_9()) return true;
    return false;
  }

  static private boolean jj_3_36()
 {
    if (jj_scan_token(NUMBER)) return true;
    return false;
  }

  static private boolean jj_3_35()
 {
    if (jj_scan_token(FALSE)) return true;
    return false;
  }

  static private boolean jj_3R_primary_225_5_25()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_34()) {
    jj_scanpos = xsp;
    if (jj_3_35()) {
    jj_scanpos = xsp;
    if (jj_3_36()) {
    jj_scanpos = xsp;
    if (jj_3_37()) {
    jj_scanpos = xsp;
    if (jj_3_38()) {
    jj_scanpos = xsp;
    if (jj_3_39()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3_34()
 {
    if (jj_scan_token(TRUE)) return true;
    return false;
  }

  static private boolean jj_3R_block_129_5_17()
 {
    if (jj_scan_token(LEFT_BRACE)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_11()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(RIGHT_BRACE)) return true;
    return false;
  }

  static private boolean jj_3_33()
 {
    if (jj_3R_primary_225_5_25()) return true;
    return false;
  }

  static private boolean jj_3_30()
 {
    if (jj_scan_token(NOT)) return true;
    return false;
  }

  static private boolean jj_3R_unary_218_5_24()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_32()) {
    jj_scanpos = xsp;
    if (jj_3_33()) return true;
    }
    return false;
  }

  static private boolean jj_3R_whileStmt_123_5_16()
 {
    if (jj_scan_token(WHILE)) return true;
    if (jj_scan_token(LEFT_PAREN)) return true;
    return false;
  }

  static private boolean jj_3_32()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_30()) {
    jj_scanpos = xsp;
    if (jj_3_31()) return true;
    }
    if (jj_3R_unary_218_5_24()) return true;
    return false;
  }

  static private boolean jj_3_26()
 {
    if (jj_scan_token(MINUS)) return true;
    return false;
  }

  static private boolean jj_3_28()
 {
    if (jj_scan_token(DIVIDE)) return true;
    return false;
  }

  static private boolean jj_3_27()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_28()) {
    jj_scanpos = xsp;
    if (jj_3_29()) return true;
    }
    if (jj_3R_unary_218_5_24()) return true;
    return false;
  }

  static private boolean jj_3R_printStmt_117_5_15()
 {
    if (jj_scan_token(PRINT)) return true;
    if (jj_3R_expression_139_5_12()) return true;
    return false;
  }

  static private boolean jj_3_4()
 {
    if (jj_scan_token(EQUAL)) return true;
    if (jj_3R_expression_139_5_12()) return true;
    return false;
  }

  static private boolean jj_3_21()
 {
    if (jj_scan_token(GREATER_EQUAL)) return true;
    return false;
  }

  static private boolean jj_3R_factor_207_5_23()
 {
    if (jj_3R_unary_218_5_24()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_27()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3_10()
 {
    if (jj_scan_token(ELSE)) return true;
    if (jj_3R_statement_94_5_11()) return true;
    return false;
  }

  static private boolean jj_3R_ifStmt_109_5_14()
 {
    if (jj_scan_token(IF)) return true;
    if (jj_scan_token(LEFT_PAREN)) return true;
    return false;
  }

  static private boolean jj_3_25()
 {
    if (jj_scan_token(PLUS)) return true;
    return false;
  }

  static private boolean jj_3_24()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_25()) {
    jj_scanpos = xsp;
    if (jj_3_26()) return true;
    }
    if (jj_3R_factor_207_5_23()) return true;
    return false;
  }

  static private boolean jj_3_18()
 {
    if (jj_scan_token(EQUAL_EQUAL)) return true;
    return false;
  }

  static private boolean jj_3R_exprStmt_103_5_13()
 {
    if (jj_3R_expression_139_5_12()) return true;
    if (jj_scan_token(SEMICOLON)) return true;
    return false;
  }

  static private boolean jj_3R_term_196_5_22()
 {
    if (jj_3R_factor_207_5_23()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_24()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3_9()
 {
    if (jj_3R_block_129_5_17()) return true;
    return false;
  }

  static private boolean jj_3_8()
 {
    if (jj_3R_whileStmt_123_5_16()) return true;
    return false;
  }

  static private boolean jj_3_7()
 {
    if (jj_3R_printStmt_117_5_15()) return true;
    return false;
  }

  static private boolean jj_3_6()
 {
    if (jj_3R_ifStmt_109_5_14()) return true;
    return false;
  }

  static private boolean jj_3_20()
 {
    if (jj_scan_token(GREATER)) return true;
    return false;
  }

  static private boolean jj_3_19()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_20()) {
    jj_scanpos = xsp;
    if (jj_3_21()) {
    jj_scanpos = xsp;
    if (jj_3_22()) {
    jj_scanpos = xsp;
    if (jj_3_23()) return true;
    }
    }
    }
    if (jj_3R_term_196_5_22()) return true;
    return false;
  }

  static private boolean jj_3R_statement_94_5_11()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_5()) {
    jj_scanpos = xsp;
    if (jj_3_6()) {
    jj_scanpos = xsp;
    if (jj_3_7()) {
    jj_scanpos = xsp;
    if (jj_3_8()) {
    jj_scanpos = xsp;
    if (jj_3_9()) return true;
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3_5()
 {
    if (jj_3R_exprStmt_103_5_13()) return true;
    return false;
  }

  static private boolean jj_3R_comparison_185_5_21()
 {
    if (jj_3R_term_196_5_22()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_19()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public SPLPrimeTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[0];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {};
	}
  static final private JJCalls[] jj_2_rtns = new JJCalls[39];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public SPLPrime(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public SPLPrime(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new SPLPrimeTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 0; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public SPLPrime(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new SPLPrimeTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new SPLPrimeTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public SPLPrime(SPLPrimeTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(SPLPrimeTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[37];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 0; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 37; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 39; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			   case 2: jj_3_3(); break;
			   case 3: jj_3_4(); break;
			   case 4: jj_3_5(); break;
			   case 5: jj_3_6(); break;
			   case 6: jj_3_7(); break;
			   case 7: jj_3_8(); break;
			   case 8: jj_3_9(); break;
			   case 9: jj_3_10(); break;
			   case 10: jj_3_11(); break;
			   case 11: jj_3_12(); break;
			   case 12: jj_3_13(); break;
			   case 13: jj_3_14(); break;
			   case 14: jj_3_15(); break;
			   case 15: jj_3_16(); break;
			   case 16: jj_3_17(); break;
			   case 17: jj_3_18(); break;
			   case 18: jj_3_19(); break;
			   case 19: jj_3_20(); break;
			   case 20: jj_3_21(); break;
			   case 21: jj_3_22(); break;
			   case 22: jj_3_23(); break;
			   case 23: jj_3_24(); break;
			   case 24: jj_3_25(); break;
			   case 25: jj_3_26(); break;
			   case 26: jj_3_27(); break;
			   case 27: jj_3_28(); break;
			   case 28: jj_3_29(); break;
			   case 29: jj_3_30(); break;
			   case 30: jj_3_31(); break;
			   case 31: jj_3_32(); break;
			   case 32: jj_3_33(); break;
			   case 33: jj_3_34(); break;
			   case 34: jj_3_35(); break;
			   case 35: jj_3_36(); break;
			   case 36: jj_3_37(); break;
			   case 37: jj_3_38(); break;
			   case 38: jj_3_39(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

}
