/* Generated By:JavaCC: Do not edit this line. SPLPrimeConstants.java */
package splprime.generated_scan;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SPLPrimeConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int NOT = 7;
  /** RegularExpression Id. */
  int PLUS = 8;
  /** RegularExpression Id. */
  int MINUS = 9;
  /** RegularExpression Id. */
  int STAR = 10;
  /** RegularExpression Id. */
  int DIVIDE = 11;
  /** RegularExpression Id. */
  int EQUAL = 12;
  /** RegularExpression Id. */
  int EQUAL_EQUAL = 13;
  /** RegularExpression Id. */
  int NOT_EQUAL = 14;
  /** RegularExpression Id. */
  int GREATER = 15;
  /** RegularExpression Id. */
  int LESS = 16;
  /** RegularExpression Id. */
  int GREATER_EQUAL = 17;
  /** RegularExpression Id. */
  int LESS_EQUAL = 18;
  /** RegularExpression Id. */
  int LEFT_PAREN = 19;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 20;
  /** RegularExpression Id. */
  int LEFT_BRACE = 21;
  /** RegularExpression Id. */
  int RIGHT_BRACE = 22;
  /** RegularExpression Id. */
  int SEMICOLON = 23;
  /** RegularExpression Id. */
  int TRUE = 24;
  /** RegularExpression Id. */
  int FALSE = 25;
  /** RegularExpression Id. */
  int AND = 26;
  /** RegularExpression Id. */
  int OR = 27;
  /** RegularExpression Id. */
  int VAR = 28;
  /** RegularExpression Id. */
  int PRINT = 29;
  /** RegularExpression Id. */
  int IF = 30;
  /** RegularExpression Id. */
  int ELSE = 31;
  /** RegularExpression Id. */
  int WHILE = 32;
  /** RegularExpression Id. */
  int STRING = 33;
  /** RegularExpression Id. */
  int NUMBER = 34;
  /** RegularExpression Id. */
  int DIGIT = 35;
  /** RegularExpression Id. */
  int IDENTIFIER = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "<SINGLE_LINE_COMMENT>",
    "\"!\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"true\"",
    "\"false\"",
    "\"and\"",
    "\"or\"",
    "\"var\"",
    "\"print\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "<STRING>",
    "<NUMBER>",
    "<DIGIT>",
    "<IDENTIFIER>",
  };

}
